# Generated by Django 4.1 on 2022-09-06 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADMINISTRATOR',
            fields=[
                ('AD_USER', models.TextField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('AD_PASSWORD', models.IntegerField(max_length=10)),
                ('AD_EMAIL', models.TimeField(max_length=50)),
                ('AD_NAMES', models.TextField(max_length=50)),
                ('AD_LASTNAMES', models.TextField(max_length=50)),
                ('AD_CELLPHONE', models.TextField(max_length=50)),
                ('AD_ROL', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BUSINESS',
            fields=[
                ('EM_ID', models.BigIntegerField(max_length=50)),
                ('EM_IDName', models.TextField(max_length=50)),
                ('EM_NIT', models.IntegerField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('EM_CITY', models.TextField(max_length=50)),
                ('EM_ADDRESS', models.TextField(max_length=50)),
                ('EM_CELLPHONE', models.TextField(max_length=10)),
                ('EM_DATECREATE', models.DateField()),
                ('EM_PRODUCTIVE_SECTOR', models.TextField(max_length=50)),
                ('EM_AD_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supermercado.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='CUSTOMERS',
            fields=[
                ('CLI_User', models.TextField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('CLI_Password', models.IntegerField()),
                ('CLI_Email', models.EmailField(max_length=254, unique=True)),
                ('CLI_Names', models.TextField(max_length=50)),
                ('CLI_LastNames', models.TextField(max_length=50)),
                ('CLI_CellPhone', models.TextField(max_length=50, unique=True)),
                ('CLI_AD_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supermercado.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='EMPLOYEES',
            fields=[
                ('EMP_USER', models.TextField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('EMP_PASSWORD', models.IntegerField(max_length=10)),
                ('EMP_EMAIL', models.TimeField(max_length=50)),
                ('EMP_NAMES', models.TextField(max_length=50)),
                ('EMP_LASTNAMES', models.TextField(max_length=50)),
                ('EMP_CELLPHONE', models.TextField(max_length=50)),
                ('EMP_ROLE', models.TextField(max_length=50)),
                ('EMP_AD_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supermercado.administrator')),
                ('EMP_EM_NIT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supermercado.business')),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTS',
            fields=[
                ('PRO_Code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('PRO_Name', models.CharField(max_length=50)),
                ('PRO_Cost', models.IntegerField()),
                ('PRO_Description', models.TextField(max_length=50)),
                ('PRO_Stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TYPEEXPENSES',
            fields=[
                ('TEGR_Code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('TEGR_NameExpenses', models.IntegerField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WORKINGHOURS',
            fields=[
                ('WORH_Code', models.TextField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('WORH_TipeHours', models.TextField(max_length=50, null=True, unique=True)),
                ('WORH_Costs', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LISTBUY',
            fields=[
                ('LBUY_Code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('LBUY_Fecha', models.DateField(auto_now=True)),
                ('LBUY_CLI_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supermercado.customers')),
                ('LBUY_PRO_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supermercado.products')),
            ],
        ),
        migrations.CreateModel(
            name='INCOME',
            fields=[
                ('ING_Code', models.IntegerField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ING_Fecha', models.DateField(auto_now=True)),
                ('ING_Quantity', models.IntegerField(max_length=10)),
                ('ING_Total', models.IntegerField(max_length=10)),
                ('ING_EMP_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supermercado.employees')),
                ('ING_EM_NIT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supermercado.business')),
                ('ING_PRO_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supermercado.products')),
            ],
        ),
        migrations.CreateModel(
            name='EXPENSES',
            fields=[
                ('EGR_Code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('EGR_Fecha', models.DateField(auto_now=True)),
                ('EGR_Total', models.IntegerField(max_length=50)),
                ('EGR_EM_NIT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supermercado.business')),
                ('EGR_TEGR_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supermercado.typeexpenses')),
            ],
        ),
        migrations.CreateModel(
            name='EMPLOYEEPAYROLL',
            fields=[
                ('PAY_Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('PAY_Hours', models.IntegerField(null=True)),
                ('PAY_ExtraHours', models.IntegerField(null=True)),
                ('PAY_parafiscal', models.IntegerField(null=True)),
                ('PAY_StartDate', models.DateField()),
                ('PAY_FinalDate', models.DateField()),
                ('PAY_TotalSalary', models.IntegerField(null=True)),
                ('PAY_EM_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supermercado.employees')),
                ('PAY_NIT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supermercado.business')),
                ('PAY_WorkingHours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supermercado.workinghours')),
            ],
        ),
    ]
