# Generated by Django 4.1 on 2022-09-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supermercado', '0003_alter_employeepayroll_pay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listbuy',
            name='LBUY_Code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
